package supersymmetry.common.metatileentities.multi.rail;

import static gregtech.api.util.RelativeDirection.*;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

import javax.annotation.Nonnull;

import net.minecraft.client.Minecraft;
import net.minecraft.client.resources.I18n;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.MobEffects;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.potion.PotionEffect;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import net.minecraftforge.items.IItemHandlerModifiable;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import cam72cam.immersiverailroading.IRItems;
import cam72cam.immersiverailroading.entity.EntityBuildableRollingStock;
import cam72cam.immersiverailroading.entity.EntityMoveableRollingStock;
import cam72cam.immersiverailroading.entity.EntityRollingStock;
import cam72cam.immersiverailroading.items.ItemRollingStock;
import cam72cam.immersiverailroading.library.Gauge;
import cam72cam.immersiverailroading.library.ItemComponentType;
import cam72cam.immersiverailroading.physics.TickPos;
import cam72cam.immersiverailroading.registry.EntityRollingStockDefinition;
import cam72cam.immersiverailroading.util.Speed;
import cam72cam.mod.entity.ModdedEntity;
import cam72cam.mod.item.ItemStack;
import cam72cam.mod.math.Vec3d;
import cam72cam.mod.world.World;
import gregtech.api.GTValues;
import gregtech.api.capability.IMultipleTankHandler;
import gregtech.api.capability.impl.ItemHandlerList;
import gregtech.api.capability.impl.MultiblockRecipeLogic;
import gregtech.api.capability.impl.NotifiableItemStackHandler;
import gregtech.api.metatileentity.MetaTileEntity;
import gregtech.api.metatileentity.interfaces.IGregTechTileEntity;
import gregtech.api.metatileentity.multiblock.IMultiblockPart;
import gregtech.api.metatileentity.multiblock.MultiblockAbility;
import gregtech.api.metatileentity.multiblock.RecipeMapMultiblockController;
import gregtech.api.pattern.BlockPattern;
import gregtech.api.pattern.FactoryBlockPattern;
import gregtech.api.pattern.PatternMatchContext;
import gregtech.api.recipes.Recipe;
import gregtech.api.unification.material.Materials;
import gregtech.api.util.GTTransferUtils;
import gregtech.client.renderer.ICubeRenderer;
import gregtech.client.renderer.texture.Textures;
import gregtech.common.ConfigHolder;
import gregtech.common.blocks.BlockMetalCasing.MetalCasingType;
import gregtech.common.blocks.BlockTurbineCasing;
import gregtech.common.blocks.MetaBlocks;
import gregtech.common.blocks.StoneVariantBlock;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import supersymmetry.api.metatileentity.multiblock.SuSyPredicates;
import supersymmetry.client.renderer.particles.SusyParticleFlame;
import supersymmetry.client.renderer.textures.SusyTextures;

public class MetaTileEntityLargeRES extends RecipeMapMultiblockController {

    private AxisAlignedBB structureAABB;
    private final Gauge gauge = Gauge.from(Gauge.STANDARD);
    private final boolean canFindTrain = true;
    private List<EntityRollingStock> rollingStocks = new ArrayList<>();
    private Int2ObjectOpenHashMap<net.minecraft.item.ItemStack> rollingStockItemStackMap = new Int2ObjectOpenHashMap<>();
    private EntityRollingStock selectedRollingStock;
    private EntityRollingStock spawnedRollingStock;
    List<ItemComponentType> spawnedRollingStackComponentsSorted;
    private NotifiableItemStackHandler trainOutputSlot;
    private NotifiableItemStackHandler trainInputSlot;
    private List<BlockPos> railPositions = new ArrayList<>();
    private UUID previousEntityUUID;

    public MetaTileEntityLargeRES(ResourceLocation metaTileEntityId) {
        super(metaTileEntityId, LargeRESRecipeMap.RES_RECIPES);
        trainOutputSlot = new NotifiableItemStackHandler(this, 1, this, true);
        trainInputSlot = new NotifiableItemStackHandler(this, 1, this, false);
        this.recipeMapWorkable = new RailroadEngineeringStationWorkable(this, trainInputSlot, trainOutputSlot);
        System.out.println("=== CONSTRUCTOR: Workable created ===");
    }

    @Override
    protected void initializeInventory() {
        super.initializeInventory();
    }

    @Override
    public MetaTileEntity createMetaTileEntity(IGregTechTileEntity iGregTechTileEntity) {
        return new MetaTileEntityLargeRES(metaTileEntityId);
    }

    @Override
    protected BlockPattern createStructurePattern() {
        return FactoryBlockPattern.start(FRONT, RIGHT, UP)
                .aisle("AAAABBBBBBBBBBBBBBBBBAAAA", "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA",
                        "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAZBBBBBBBBBBBBBBBBBBAAA", "AAAYBBBBBBBBBBBBBBBBBBAAA", "AAAXBBBBBBBBBBBBBBBBBBAAA",
                        "AAATBBBBBBBBBBBBBBBBBBAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAABBBBBBBBBBBBBBBBBBBAAA",
                        "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA", "AAAABBBBBBBBBBBBBBBBBAAAA",
                        "AAAABBBBBBBBBBBBBBBBBAAAA", "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA",
                        "AAABBBBBBBBBBBBBBBBBBBAAA", "AAABBBBBBBBBBBBBBBBBBBAAA", "AAAABBBBBBBBBBBBBBBBBAAAA")
                .aisle("AAAABBAAAAADDDAAAAABBAAAA", "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA",
                        "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAMBBBAAAADDDAAAABBBBAAA", "AAAYBBBAAAADDDAAAABBBBAAA", "AAAXBBBAAAADDDAAAABBBBAAA",
                        "AAACBBBAAAADDDAAAABBBBAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAABBBBAAAADDDAAAABBBBAAA",
                        "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA", "AAAABBAAAAADDDAAAAABBAAAA",
                        "AAAABBAAAAADDDAAAAABBAAAA", "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA",
                        "AAABBBBAAAADDDAAAABBBBAAA", "AAABBBBAAAADDDAAAABBBBAAA", "AAAABBAAAAADDDAAAAABBAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAABBAAAAAAAAAAAAABBAAAA", "AAABFFBAAAAAAAAAAABFFBAAA",
                        "AAABFFBAAAAAAAAAAABFFBAAA", "AAAABBAAAAAAAAAAAAABBAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAABBAAAAAAAAAAAAABBAAAA", "AAABFFBAAAAAAAAAAABFFBAAA", "AAABFFBAAAAAAAAAAABFFBAAA",
                        "AAAABBAAAAAAAAAAAAABBAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAABBAAAAAAAAAAAAABBAAAA",
                        "AAABFFBAAAAAAAAAAABFFBAAA", "AAABFFBAAAAAAAAAAABFFBAAA", "AAAABBAAAAAAAAAAAAABBAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAABBAAAAAAAAAAAAABBAAAA", "AAABFFBAAAAAAAAAAABFFBAAA",
                        "AAABFFBAAAAAAAAAAABFFBAAA", "AAAABBAAAAAAAAAAAAABBAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAGGAAAGGAAAAAAAAA",
                        "AAAAAAAAAGGAAAGGAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAGGAAAGGAAAAAAAAA", "AAAFFFFAAGGAAAGGAAFFFFAAA",
                        "AAAFFFFAAGGAAAGGAAFFFFAAA", "AAAAAAAAAGGAAAGGAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAGGAAAGGAAAFFAAAA", "AAAAFFAAAGGAAAGGAAAFFAAAA", "FFFFHHFFFHHFFFHHFFFHHFFFF",
                        "FFFFHHFFFHHFFFHHFFFHHFFFF", "AAAAFFAAAGGAAAGGAAAFFAAAA", "AAAAFFAAAGGAAAGGAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAGGAAAGGAAAFFAAAA", "AAAAFFAAAGGAAAGGAAAFFAAAA", "FFFFHHFFFHHFFFHHFFFHHFFFF",
                        "FFFFHHFFFHHFFFHHFFFHHFFFF", "AAAAFFAAAGGAAAGGAAAFFAAAA", "AAAAFFAAAGGAAAGGAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAFFAAAAAAAAAAAAAFFAAAA",
                        "AAAAFFAAAAAAAAAAAAAFFAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAGGAAAGGAAAAAAAAA", "AAAFFFFFFGGAAAGGFFFFFFAAA",
                        "AAAFFFFFFGGAAAGGFFFFFFAAA", "AAAAAAAAAGGAAAGGAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAFFFGGAAAGGFFFAAAAAA",
                        "AAAAAAFFFGGAAAGGFFFAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAAAAAAAA")
                .where('A', any())
                .where('B', states(MetaBlocks.STONE_BLOCKS.get(StoneVariantBlock.StoneVariant.SMOOTH)
                        .getState(StoneVariantBlock.StoneType.CONCRETE_LIGHT)))
                .where('C', selfPredicate())
                .where('D', SuSyPredicates.rails())
                .where('F', frames(Materials.Steel))
                .where('G', states(MetaBlocks.METAL_CASING.getState(MetalCasingType.STEEL_SOLID))) // Meta: 4)
                .where('H',
                        states(MetaBlocks.TURBINE_CASING.getState(BlockTurbineCasing.TurbineCasingType.STEEL_GEARBOX))) // Meta:
                                                                                                                        // 1)
                .where('X', abilities(MultiblockAbility.IMPORT_ITEMS)) // input bus
                .where('Y', abilities(MultiblockAbility.IMPORT_FLUIDS)) // input hatch
                .where('M', abilities(MultiblockAbility.MAINTENANCE_HATCH))
                .where('Z', abilities(MultiblockAbility.MUFFLER_HATCH))
                .where('T', abilities(MultiblockAbility.INPUT_ENERGY))
                .build();
    }

    @Override
    public void addInformation(net.minecraft.item.ItemStack stack, @Nullable net.minecraft.world.World world,
                               @NotNull List<String> tooltip, boolean advanced) {
        tooltip.add(I18n.format("susy.machine.large_railroad_engineering_station.tip"));
        super.addInformation(stack, world, tooltip, advanced);
    }

    @Override
    public ICubeRenderer getBaseTexture(IMultiblockPart iMultiblockPart) {
        return Textures.CLEAN_STAINLESS_STEEL_CASING;
    }

    @Nonnull
    @Override
    protected ICubeRenderer getFrontOverlay() {
        return SusyTextures.RAILROAD_ENGINEERING_STATION_OVERLAY;
    }

    @Override
    protected void formStructure(PatternMatchContext context) {
        super.formStructure(context);
        this.setStructureAABB();
        this.railPositions.clear();

        EnumFacing right = getFrontFacing().rotateY();
        BlockPos aisleBase = getPos().offset(getFrontFacing().getOpposite(), 1);

        System.out.println("Controller: " + getPos() + " facing: " + getFrontFacing());
        System.out.println("AisleBase: " + aisleBase + " right: " + right);

        for (int offset = -12; offset <= 12; offset++) {
            BlockPos candidate = aisleBase.offset(right, offset);
            net.minecraft.block.Block block = getWorld().getBlockState(candidate).getBlock();
            System.out.println("  offset " + offset + " pos " + candidate + " = " + block.getRegistryName());
            if (block.getRegistryName() != null &&
                    block.getRegistryName().toString().contains("block_rail")) {
                this.railPositions.add(candidate);
            }
        }
    }

    @Override
    protected void updateFormedValid() {
        super.updateFormedValid();

        if (isFirstTick()) {
            List<ModdedEntity> trains = getWorld().getEntitiesWithinAABB(ModdedEntity.class, this.structureAABB);
            if (!trains.isEmpty()) {
                for (ModdedEntity forgeTrainEntity : trains) {
                    if (forgeTrainEntity.getSelf() instanceof EntityRollingStock rollingStock) {
                        if (rollingStock.getUUID().equals(this.previousEntityUUID)) {
                            this.spawnedRollingStock = rollingStock;
                            this.spawnedRollingStackComponentsSorted = rollingStock.getDefinition().getItemComponents()
                                    .stream()
                                    .sorted(Comparator.comparingInt(i -> i.ordinal()))
                                    .collect(Collectors.toList());
                            break;
                        }
                    }
                }
            }
        }

        if (this.getOffsetTimer() % 20 == 1) {
            if (recipeMapWorkable.isActive()) {
                List<EntityPlayer> players = getWorld().getEntitiesWithinAABB(EntityPlayer.class, this.structureAABB);
                for (EntityPlayer player : players) {
                    player.addPotionEffect(new PotionEffect(MobEffects.MINING_FATIGUE, 21, 1));
                }
            }

            if (this.canFindTrain) {
                List<ModdedEntity> trains = getWorld().getEntitiesWithinAABB(ModdedEntity.class, this.structureAABB);
                this.rollingStocks = new ArrayList<>();

                if (!trains.isEmpty()) {
                    for (ModdedEntity forgeTrainEntity : trains) {
                        if (forgeTrainEntity.getSelf() instanceof EntityRollingStock rollingStock) {
                            this.rollingStocks.add(rollingStock);
                        }
                    }
                }

                // This logic may need to be cleaned up
                // Currently this just selects the first train entity it found
                // Probably using the UI, showing shows each found entity
                // And the player select one specific entity
                if (!this.rollingStocks.isEmpty()) {
                    this.setSelectedEntity(this.rollingStocks.get(0));
                } else {
                    this.trainInputSlot.setStackInSlot(
                            0,
                            net.minecraft.item.ItemStack.EMPTY);
                    this.selectedRollingStock = null;
                }
            }
        }
    }

    @Override
    public void update() {
        super.update();
        if (this.getWorld().isRemote && this.isActive() && this.getOffsetTimer() % 2 == 0) {
            this.spawnWorkingParticles();
        }
    }

    private net.minecraft.item.ItemStack getTrainItemStackFromCache(EntityRollingStock rollingStock) {
        net.minecraft.item.ItemStack is;
        int id = rollingStock.getId();
        if ((is = this.rollingStockItemStackMap.get(id)) == null) {
            if ((is = this.getTrainItemStack(rollingStock)) != null) {
                this.rollingStockItemStackMap.put(id, is);
            }
        }
        return is.copy();
    }

    private net.minecraft.item.ItemStack getTrainItemStack(EntityRollingStock rollingStock) {
        // What the actual fucking shit is wrong with the shit fucking stupid fucking IR codebase I fucking cant
        // why the fuck is there no fuckingapi what the fuck
        // what hte fuck is an Itemstack.internal why the fuck would you do this
        // I will fucjing stab you to death with your stupid giant fucking wrench

        EntityRollingStockDefinition def = rollingStock.getDefinition();
        ItemStack stack = new ItemStack(IRItems.ITEM_ROLLING_STOCK, 1);
        ItemRollingStock.Data data = new ItemRollingStock.Data(stack);
        data.def = def;
        data.gauge = this.gauge;
        data.write();
        return stack.internal;
    }

    private void setSelectedEntity(EntityRollingStock rollingStock) {
        this.selectedRollingStock = rollingStock;
        this.trainInputSlot.setStackInSlot(
                0,
                this.getTrainItemStackFromCache(this.selectedRollingStock));
    }

    public float getTrainSpawnAngle() {
        if (this.frontFacing == EnumFacing.NORTH) {
            return 90;
        } else if (this.frontFacing == EnumFacing.EAST) {
            return 180;
        } else if (this.frontFacing == EnumFacing.SOUTH) {
            return 270;
        } else {
            return 0;
        }
    }

    public BlockPos getRailPos() {
        EnumFacing front = getFrontFacing();
        // Rails are 1 block back from controller, centered (no right offset)
        return getPos().offset(front.getOpposite(), 9);
    }

    public EntityRollingStock spawnRollingStock(ItemStack stack) {
        ItemRollingStock.Data data = new ItemRollingStock.Data(stack);
        EntityRollingStockDefinition def = data.def;

        if (def != null) {
            World irWorld = World.get(getWorld());
            BlockPos railPos = railPositions.isEmpty() ? getRailPos() : railPositions.get(railPositions.size() / 2);
            System.out.println("Controller pos: " + getPos());
            System.out.println("Facing: " + getFrontFacing());
            System.out.println("Rail positions found: " + railPositions.size());
            for (BlockPos p : railPositions) {
                System.out.println("  Rail: " + p);
            }
            System.out.println("Selected rail pos: " + railPos);

            TickPos tp = new TickPos(
                    0, Speed.ZERO,
                    new Vec3d(railPos.getX() + 0.5, railPos.getY() + 0.0625, railPos.getZ() + 0.5),
                    0, 0, 0, 0.0F, false);

            EntityRollingStock stock = def.spawn(irWorld, tp.position, this.getTrainSpawnAngle(), gauge, data.texture);

            if (stock instanceof EntityMoveableRollingStock mrs) {
                tp.speed = Speed.ZERO;
                mrs.initPositions(tp);
            }

            if (stock instanceof EntityBuildableRollingStock) {
                this.spawnedRollingStackComponentsSorted = def.getItemComponents().stream()
                        .sorted(Comparator.comparingInt(ItemComponentType::ordinal))
                        .collect(Collectors.toList());
                this.spawnedRollingStockAddedToWorld = false; // not yet in world
            } else {
                this.setStockInWorld(stock);
                this.spawnedRollingStockAddedToWorld = true;
            }

            return stock;
        }
        return null;
    }

    private boolean spawnedRollingStockAddedToWorld = false;

    public void updateSpawnedStock(float recipeProgress) {
        if (this.spawnedRollingStock instanceof EntityBuildableRollingStock buildableRollingStock &&
                spawnedRollingStackComponentsSorted != null && !spawnedRollingStackComponentsSorted.isEmpty()) {

            if (!this.spawnedRollingStockAddedToWorld) {
                this.setStockInWorld(this.spawnedRollingStock);
                this.spawnedRollingStockAddedToWorld = true;
            }

            int idx = (int) (recipeProgress * spawnedRollingStackComponentsSorted.size());
            buildableRollingStock.setComponents(spawnedRollingStackComponentsSorted.subList(0, idx));
        }
    }

    public void completeSpawnedStock() {
        if (this.spawnedRollingStock instanceof EntityBuildableRollingStock buildableRollingStock &&
                spawnedRollingStackComponentsSorted.size() > 0) {
            // Finish the rolling stock
            buildableRollingStock.setComponents(buildableRollingStock.getItemComponents());
        } else {
            this.setStockInWorld(this.spawnedRollingStock);
        }
        this.spawnedRollingStock = null;
        this.spawnedRollingStockAddedToWorld = false;
        this.spawnedRollingStackComponentsSorted = null;
    }

    public void setStockInWorld(EntityRollingStock stock) {
        World irWorld = World.get(getWorld());
        irWorld.spawnEntity(stock);
    }

    @Override
    public void invalidateStructure() {
        super.invalidateStructure();
        this.structureAABB = null;
        this.selectedRollingStock = null;
        this.spawnedRollingStockAddedToWorld = false;
        this.railPositions.clear();
        if (this.spawnedRollingStock != null) {
            this.spawnedRollingStock.kill();
            this.spawnedRollingStock = null;
        }
        this.rollingStocks = new ArrayList<>();
    }

    @Override
    public NBTTagCompound writeToNBT(NBTTagCompound data) {
        if (this.spawnedRollingStock != null) {
            UUID rollingStockEntityID = spawnedRollingStock.getUUID();
            data.setUniqueId("RollingStockEntityID", rollingStockEntityID);
        }
        return super.writeToNBT(data);
    }

    @Override
    public void readFromNBT(NBTTagCompound data) {
        // UUIDs get saved as two IDs I guess
        super.readFromNBT(data);
        if (data.hasKey("RollingStockEntityIDMost")) {
            this.setStructureAABB();
            this.previousEntityUUID = data.getUniqueId("RollingStockEntityID");
        }
    }

    @Override
    public void onRemoval() {
        if (this.spawnedRollingStock != null) {
            this.spawnedRollingStock.kill();
        }
        super.onRemoval();
    }

    @Override
    public void invalidate() {
        super.invalidate();
        if (!getWorld().isRemote) {

            if (this.spawnedRollingStock != null) {
                this.spawnedRollingStock.kill();
            }
        }
    }

    @Override
    public boolean getIsWeatherOrTerrainResistant() {
        return true;
    }

    @Override
    public boolean isMultiblockPartWeatherResistant(@NotNull IMultiblockPart part) {
        return true;
    }

    public void setStructureAABB() {
        BlockPos pos = this.getPos();
        // Convert your relative coordinates to absolute world coordinates
        this.structureAABB = new AxisAlignedBB(
                pos.getX() - 3, pos.getY() - 24, pos.getZ() - 1,
                pos.getX() + 22, pos.getY() + 42, pos.getZ() + 17);
    }

    @SideOnly(Side.CLIENT)
    public void spawnWorkingParticles() {
        SusyParticleFlame spark = new SusyParticleFlame(
                this.getWorld(),
                this.getPos().getX() + this.getFrontFacing().getOpposite().getDirectionVec().getX() * 5 +
                        (1 - this.getFrontFacing().getOpposite().getDirectionVec().getX()) * 3 *
                                (GTValues.RNG.nextFloat() - 0.5),
                this.getPos().getY() + 0.5,
                this.getPos().getZ() + this.getFrontFacing().getOpposite().getDirectionVec().getZ() * 5 +
                        (1 - this.getFrontFacing().getOpposite().getDirectionVec().getZ()) * 3 *
                                (GTValues.RNG.nextFloat() - 0.5),
                (GTValues.RNG.nextFloat() - 0.5) * 1.2F,
                GTValues.RNG.nextFloat() * 1.5F,
                (GTValues.RNG.nextFloat() - 0.5) * 1.2F);
        Minecraft.getMinecraft().effectRenderer.addEffect(spark);
    }

    protected static class RailroadEngineeringStationWorkable extends MultiblockRecipeLogic {

        NotifiableItemStackHandler trainOutput;
        NotifiableItemStackHandler trainInput;

        public RailroadEngineeringStationWorkable(RecipeMapMultiblockController tileEntity,
                                                  NotifiableItemStackHandler trainInput,
                                                  NotifiableItemStackHandler trainOutput) {
            super(tileEntity);
            this.trainInput = trainInput;
            this.trainOutput = trainOutput;
            System.out.println("RailroadEngineeringStationWorkable constructed!");
            System.out.println("  Train input: " + trainInput);
            System.out.println("  Train output: " + trainOutput);
        }

        public MetaTileEntityLargeRES getMetaTileEntity() {
            return (MetaTileEntityLargeRES) super.getMetaTileEntity();
        }

        @Override
        protected IItemHandlerModifiable getInputInventory() {
            IItemHandlerModifiable inputs = super.getInputInventory();
            List<IItemHandlerModifiable> inputList = new ArrayList<>();
            if (inputs != null) inputList.add(inputs);
            inputList.add(trainInput);
            return new ItemHandlerList(inputList);
        }

        @Override
        protected IItemHandlerModifiable getOutputInventory() {
            return trainOutput;
        }

        @Override
        public void update() {
            super.update();

            if (getMetaTileEntity().getOffsetTimer() % 40 == 0) {
                System.out.println("=== WORKABLE UPDATE [" +
                        (getMetaTileEntity().getWorld().isRemote ? "CLIENT" : "SERVER") + "] ===");
                System.out.println("Is active: " + isActive());
                System.out.println("Is working enabled: " + isWorkingEnabled());
                System.out.println("Can progress: " + canRecipeProgress);
                System.out.println("Progress: " + progressTime + "/" + maxProgressTime);
                System.out.println("Recipe EU/t: " + recipeEUt);
            }
        }

        @Override
        protected Recipe findRecipe(long maxVoltage, IItemHandlerModifiable inputs, IMultipleTankHandler fluidInputs) {
            System.out.println("=== FINDING RECIPE ===");
            System.out.println("Max voltage: " + maxVoltage);
            System.out.println("Input handler slots: " + inputs.getSlots());

            // Log all items in input slots
            for (int i = 0; i < inputs.getSlots(); i++) {
                net.minecraft.item.ItemStack stack = inputs.getStackInSlot(i);
                if (!stack.isEmpty()) {
                    System.out.println("  Slot " + i + ": " + stack + " x" + stack.getCount());
                }
            }

            Recipe recipe = super.findRecipe(maxVoltage, inputs, fluidInputs);

            System.out.println("Found recipe: " + recipe);
            System.out.println("=== RECIPE SEARCH COMPLETE ===");

            return recipe;
        }

        @Override
        protected boolean setupAndConsumeRecipeInputs(@NotNull Recipe recipe,
                                                      @NotNull IItemHandlerModifiable importInventory,
                                                      @NotNull IMultipleTankHandler importFluids) {
            // Let super run first to set itemOutputs, fluidOutputs, recipeEUt, etc.
            boolean result = super.setupAndConsumeRecipeInputs(recipe, importInventory, importFluids);

            if (result) {
                MetaTileEntityLargeRES mte = this.getMetaTileEntity();

                // Kill existing selected rolling stock
                if (this.trainInput.getStackInSlot(0).isEmpty() && mte.selectedRollingStock != null) {
                    mte.selectedRollingStock.kill();
                    mte.selectedRollingStock = null;
                }

                // Spawn the new rolling stock
                mte.spawnedRollingStock = mte.spawnRollingStock(new ItemStack(recipe.getOutputs().get(0)));
            }

            return result;
        }

        @Override
        protected void updateRecipeProgress() {
            if (this.canRecipeProgress && this.drawEnergy(this.recipeEUt, true)) {
                this.drawEnergy(this.recipeEUt, false);

                this.getMetaTileEntity().updateSpawnedStock((float) this.progressTime / this.maxProgressTime);

                if (++this.progressTime > this.maxProgressTime) {
                    this.completeRecipe();
                }

                if (this.hasNotEnoughEnergy && this.getEnergyInputPerSecond() > 19L * (long) this.recipeEUt) {
                    this.hasNotEnoughEnergy = false;
                }
            } else if (this.recipeEUt > 0) {
                this.hasNotEnoughEnergy = true;
                if (this.progressTime >= 2) {
                    if (ConfigHolder.machines.recipeProgressLowEnergy) {
                        this.progressTime = 1;
                    } else {
                        this.progressTime = Math.max(1, this.progressTime - 2);
                    }
                }
            }
        }

        @Override
        protected void completeRecipe() {
            GTTransferUtils.addFluidsToFluidHandler(this.getOutputTank(), false, this.fluidOutputs);
            // Don't output items - train is already on rails
            this.progressTime = 0;
            this.setMaxProgress(0);
            this.recipeEUt = 0;
            this.fluidOutputs = null;
            this.itemOutputs = null;
            this.hasNotEnoughEnergy = false;
            this.wasActiveAndNeedsUpdate = true;
            this.parallelRecipesPerformed = 0;
            this.overclockResults = new int[] { 0, 0 };
            this.getMetaTileEntity().completeSpawnedStock();

            System.out.println("Recipe completed!");
        }
    }

    @Override
    public boolean allowsExtendedFacing() {
        return false;
    }

    @Override
    public String getMetaName() {
        return "large_railroad_engineering_station";
    }
}
