name: Build Artifacts

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Build Project
        run: gradle build --warning-mode all --build-cache

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v5
        with:
          name: Artifacts
          path: build/libs
